### ISSUE TITLE
训练样本是否需要[CLS]和<|endofpiece|>？

### ISSUE THREAD

**Issue by Jong-Won** [yongzhuo/chatglm-maths#10]
huggingface inference格式是：
[CLS] 凯旋门位于意大利米兰市古城堡旁。1807年为纪念拿破仑军队攻克米兰城而建,门高25米,顶上矗立两武士青铜古兵车铸像。 [gMASK] <|endoftext|> <|startofpiece|> 门上有许多精美的雕刻,其中最引人注目的是一对屹立在门顶上的巨型青铜华表,华表上有两只威风凛凛的雄狮,一只象征拿破仑,一只象征米兰人民。 <|endofpiece|>

但是作者在最新更新的readme里面训练时没有`[CLS]`和`<|endoftext|>`, 请问这两个token在训练时有必要吗？

chatglm-maths在测试的时候时这种格式吗？[CLS] ... [gMASK] <|endoftext|> <|startofpiece|> ... <|endofpiece|>

**Comment by yongzhuo** [comment]
chatglm的tokenizer会自带下划线和尾巴，样例：问题: '-' + "1+1=" + 【gMASK】+【BOS】; 答案: '-' + "1+1=2" + 【EOS】。
你可以用ChatGLMTokenizer.build_inputs_with_special_tokens(token_ids_0, token_ids_1).
当然这个代码里边也实现了，详见c00_toy_lora_train_6b.py的Generator.__iter__
