### ISSUE TITLE
ValueError: 150004 is not in list

### ISSUE THREAD

**Issue by Chenzongchao** [yongzhuo/chatglm-maths#3]
context_length = seq.index(bos_token_id) + 1

ValueError: 150004 is not in list
大佬用自己数据集爆这个错咋办

**Comment by yongzhuo** [comment]
训练的话估计是截断了，__iter__ 生成的数据可以改成
```
x_encode = tokenizer.encode(x)  # encode自己多生成了一个空格_
y_encode = tokenizer.encode(y)[:-2]
if len(x) + len(y) > (MAX_LENGTH_Q + MAX_LENGTH_A):
    x = x[:MAX_LENGTH_Q]
    y = y[:MAX_LENGTH_A]
    if ID_gMASK not in x:
        x += [ID_gMASK]
    if ID_BOS not in x:
        x += [ID_BOS]
```

**Comment by Chenzongchao** [comment]
老哥想用多卡训练用什么方法比较好

**Comment by qishisurenhhh** [comment]
这个问题是怎么造成的

**Comment by yongzhuo** [comment]
最新代码已修复，截断造成的，chatglm输入最后需要接[ID_gMASK], [ID_BOS]

**Comment by YSLLYW** [comment]
> 最新代码已修复，截断造成的，chatglm输入最后需要接[ID_gMASK], [ID_BOS]

没有修复啊，多卡还是报错

**Comment by YSLLYW** [comment]
> 最新代码已修复，截断造成的，chatglm输入最后需要接[ID_gMASK], [ID_BOS]

ValueError: 150004 is not in list，和ValueError: 130004 is not in list
