### ISSUE TITLE
probs is nan

### ISSUE THREAD

**Issue by yangzhipeng1108** [yongzhuo/chatglm-maths#4]
Traceback (most recent call last):
  File "t10_toy_trl_train_ppo.py", line 178, in <module>
    response_tensor = respond_to_batch_new(model_ref, query_tensor,
  File "t10_toy_trl_train_ppo.py", line 60, in respond_to_batch_new
    next_token = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

**Comment by yongzhuo** [comment]
可能的原因是dtype不一致，或者是训练问题

**Comment by yangzhipeng1108** [comment]
tks

**Comment by yongzhuo** [comment]
此外，int8训练layer_norm层最好是float32，否则会不稳定，LN权重溢出，为Nan。
需要改两个地方:
1. int8加载好ChatGLMForConditionalGeneration后需要改变LN的数据类型。
```python
from peft import prepare_model_for_int8_training
model = prepare_model_for_int8_training(model,
        use_gradient_checkpointing=True,
        output_embedding_layer_name="lm_head",
        # layer_norm_names=[],
        layer_norm_names=["post_attention_layernorm",
                          "final_layernorm",
                          "input_layernorm"
                          ]
        )
```

2. 步骤1会导致dtype不一致，然后所有LN输入输出都需要变换数据类型。修改modeling_chatglm.py
```python
如
1.attention_input = self.input_layernorm(hidden_states)
 改为    
attention_input = self.input_layernorm(hidden_states.to(self.input_layernorm.weight.dtype))

2. hidden_states = self.final_layernorm(hidden_states)
 改为
hidden_states = self.final_layernorm(hidden_states.to(self.final_layernorm.weight.dtype))

```

**Comment by yongzhuo** [comment]
最新代码已修复
