### ISSUE TITLE
  python3 c00_toy_lora_train_6b.py        RuntimeError: Internal: [MASK] is already defined.

### ISSUE THREAD

**Issue by ARES3366** [yongzhuo/chatglm-maths#8]
python3 c00_toy_lora_train_6b.py
/data/chatglm-ppo/chatglm-maths
/opt/conda/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
generator_calculate_line: ('13+75=', '13+75=88')
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /data/chatglm-ppo/chatglm-maths/chatglm_maths/c00_toy_lora_train_6b.py:340 in <module>           │
│                                                                                                  │
│   337                                                                                            │
│   338 # The argument `trust_remote_code` is to be used with Auto classes. It has no effect her   │
│   339 chatglm_config = ChatGLMConfig.from_pretrained(pretrained_model_name_or_path)              │
│ ❱ 340 tokenizer = ChatGLMTokenizer.from_pretrained(pretrained_model_name_or_path)                │
│   341 text = ("1、2", "3、4")                                                                    │
│   342 x_encode = tokenizer.encode(text[0])                                                       │
│   343 y_encode = tokenizer.encode(text[1])                                                       │
│                                                                                                  │
│ /opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1811 in          │
│ from_pretrained                                                                                  │
│                                                                                                  │
│   1808 │   │   │   else:                                                                         │
│   1809 │   │   │   │   logger.info(f"loading file {file_path} from cache at {resolved_vocab_fil  │
│   1810 │   │                                                                                     │
│ ❱ 1811 │   │   return cls._from_pretrained(                                                      │
│   1812 │   │   │   resolved_vocab_files,                                                         │
│   1813 │   │   │   pretrained_model_name_or_path,                                                │
│   1814 │   │   │   init_configuration,                                                           │
│                                                                                                  │
│ /opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1965 in          │
│ _from_pretrained                                                                                 │
│                                                                                                  │
│   1962 │   │                                                                                     │
│   1963 │   │   # Instantiate tokenizer.                                                          │
│   1964 │   │   try:                                                                              │
│ ❱ 1965 │   │   │   tokenizer = cls(*init_inputs, **init_kwargs)                                  │
│   1966 │   │   except OSError:                                                                   │
│   1967 │   │   │   raise OSError(                                                                │
│   1968 │   │   │   │   "Unable to load vocabulary from file. "                                   │
│                                                                                                  │
│ /data/chatglm-ppo/chatglm-maths/chatglm_maths/models/tokenization_chatglm.py:225 in __init__     │
│                                                                                                  │
│   222 │   │   self.mask_token = mask_token                                                       │
│   223 │   │   self.gMASK_token = gmask_token                                                     │
│   224 │   │                                                                                      │
│ ❱ 225 │   │   self.sp_tokenizer = SPTokenizer(vocab_file)                                        │
│   226 │   │                                                                                      │
│   227 │   │   """ Initialisation """                                                             │
│   228                                                                                            │
│                                                                                                  │
│ /data/chatglm-ppo/chatglm-maths/chatglm_maths/models/tokenization_chatglm.py:39 in __init__      │
│                                                                                                  │
│    36 │   │   self.special_tokens = ["[MASK]", "[gMASK]", "[sMASK]", "<unused_0>", "<sop>", "<   │
│    37 │   │   self.max_blank_length = max_blank_length                                           │
│    38 │   │   self.byte_fallback = byte_fallback                                                 │
│ ❱  39 │   │   self.text_tokenizer = self._build_text_tokenizer(encode_special_tokens=False)      │
│    40 │   │   self.special_text_tokenizer = self._build_text_tokenizer(encode_special_tokens=T   │
│    41 │                                                                                          │
│    42 │   @staticmethod                                                                          │
│                                                                                                  │
│ /data/chatglm-ppo/chatglm-maths/chatglm_maths/models/tokenization_chatglm.py:72 in               │
│ _build_text_tokenizer                                                                            │
│                                                                                                  │
│    69 │                                                                                          │
│    70 │   def _build_text_tokenizer(self, encode_special_tokens=False):                          │
│    71 │   │   tokenizer = TextTokenizer(self.vocab_file)                                         │
│ ❱  72 │   │   self._configure_tokenizer(                                                         │
│    73 │   │   │   tokenizer, self.special_tokens, self.max_blank_length, self.byte_fallback, e   │
│    74 │   │   )                                                                                  │
│    75 │   │   return tokenizer                                                                   │
│                                                                                                  │
│ /data/chatglm-ppo/chatglm-maths/chatglm_maths/models/tokenization_chatglm.py:68 in               │
│ _configure_tokenizer                                                                             │
│                                                                                                  │
│    65 │   │   │   │   text_tokenizer.proto.pieces.append(                                        │
│    66 │   │   │   │   │   sp_model.ModelProto.SentencePiece(piece="<0x{:02X}>".format(i), scor   │
│    67 │   │   │   │   )                                                                          │
│ ❱  68 │   │   text_tokenizer.refresh()                                                           │
│    69 │                                                                                          │
│    70 │   def _build_text_tokenizer(self, encode_special_tokens=False):                          │
│    71 │   │   tokenizer = TextTokenizer(self.vocab_file)                                         │
│                                                                                                  │
│ /opt/conda/lib/python3.10/site-packages/icetk/text_tokenizer.py:31 in refresh                    │
│                                                                                                  │
│   28 │                                                                                           │
│   29 │   def refresh(self):                                                                      │
│   30 │   │   self.sp = spm.SentencePieceProcessor()                                              │
│ ❱ 31 │   │   self.sp.Load(model_proto=self.proto.SerializeToString())                            │
│   32 │   │   self.num_tokens = self.sp.vocab_size()                                              │
│   33 │                                                                                           │
│   34 │   def add_special_tokens(self, tokens):                                                   │
│                                                                                                  │
│ /opt/conda/lib/python3.10/site-packages/sentencepiece/__init__.py:904 in Load                    │
│                                                                                                  │
│    901 │     if model_file and model_proto:                                                      │
│    902 │   │   raise RuntimeError('model_file and model_proto must be exclusive.')               │
│    903 │     if model_proto:                                                                     │
│ ❱  904 │   │   return self.LoadFromSerializedProto(model_proto)                                  │
│    905 │     return self.LoadFromFile(model_file)                                                │
│    906                                                                                           │
│    907                                                                                           │
│                                                                                                  │
│ /opt/conda/lib/python3.10/site-packages/sentencepiece/__init__.py:250 in LoadFromSerializedProto │
│                                                                                                  │
│    247 │   __swig_destroy__ = _sentencepiece.delete_SentencePieceProcessor                       │
│    248 │                                                                                         │
│    249 │   def LoadFromSerializedProto(self, serialized):                                        │
│ ❱  250 │   │   return _sentencepiece.SentencePieceProcessor_LoadFromSerializedProto(self, seria  │
│    251 │                                                                                         │
│    252 │   def SetEncodeExtraOptions(self, extra_option):                                        │
│    253 │   │   return _sentencepiece.SentencePieceProcessor_SetEncodeExtraOptions(self, extra_o  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Internal: [MASK] is already defined.

麻烦问下大佬这是什么问题？

 python3 c00_toy_lora_train_6b.py

**Comment by yongzhuo** [comment]
trust_remote_code=False试试，最新的远程代码、权重已经变了。该代码是原始的，已经和最新的官方代码、权重等有所差异，可能不适用了，谨慎参考

**Comment by ARES3366** [comment]
是的，官方更新比较快。大佬，有没有适用官方最新代码的ppo算法代码？

**Comment by yongzhuo** [comment]
害，还没有，有时间我更新一下

**Comment by ARES3366** [comment]
好的，感谢大佬

**Comment by yongzhuo** [comment]
已更新
