### ISSUE TITLE
ValueError: 130004 is not in list   大佬，这是什么错误？

### ISSUE THREAD

**Issue by ARES3366** [yongzhuo/chatglm-maths#9]
/data/chatglm-ppo/chatglm-maths/chatglm_maths/t10_toy_trl_train_ppo.py:58 in                     │
│ respond_to_batch_new                                                                             │
│                                                                                                  │
│    55 │   for i in range(txt_len):                                                               │
│    56 │   │   try:                                                                               │
│    57 │   │   │   # Get Logits                                                                   │
│ ❱  58 │   │   │   outputs = model(torch.cat([start_ids, end_ids], dim=-1))                       │
│    59 │   │   │   next_token_logits = outputs[0][:, -1, :]                                       │
│    60 │   │   │   next_token_logits = top_k_top_p_filtering(next_token_logits, top_k=top_k, to   │
│    61 │   │   │   # Sample                                                                       │
│                                                                                                  │
│ /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1501 in _call_impl            │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ /data/trl/trl/models/modeling_value_head.py:161 in forward                                       │
│                                                                                                  │
│   158 │   │   """                                                                                │
│   159 │   │   kwargs["output_hidden_states"] = True  # this had already been set in the LORA /   │
│   160 │   │                                                                                      │
│ ❱ 161 │   │   base_model_output = self.pretrained_model(                                         │
│   162 │   │   │   input_ids=input_ids,                                                           │
│   163 │   │   │   past_key_values=past_key_values,                                               │
│   164 │   │   │   attention_mask=attention_mask,                                                 │
│                                                                                                  │
│ /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1501 in _call_impl            │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ /data/chatglm-ppo/chatglm-maths/chatglm_maths/models/modeling_chatglm.py:1119 in forward         │
│                                                                                                  │
│   1116 │   │   use_cache = use_cache if use_cache is not None else self.config.use_cache         │
│   1117 │   │   return_dict = return_dict if return_dict is not None else self.config.use_return  │
│   1118 │   │                                                                                     │
│ ❱ 1119 │   │   transformer_outputs = self.transformer(                                           │
│   1120 │   │   │   input_ids=input_ids,                                                          │
│   1121 │   │   │   position_ids=position_ids,                                                    │
│   1122 │   │   │   attention_mask=attention_mask,                                                │
│                                                                                                  │
│ /opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py:1501 in _call_impl            │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ /data/chatglm-ppo/chatglm-maths/chatglm_maths/models/modeling_chatglm.py:917 in forward          │
│                                                                                                  │
│    914 │   │   │   seq = input_ids[0].tolist()                                                   │
│    915 │   │   │                                                                                 │
│    916 │   │   │   if attention_mask is None:                                                    │
│ ❱  917 │   │   │   │   attention_mask = self.get_masks(                                          │
│    918 │   │   │   │   │   seq=seq,                                                              │
│    919 │   │   │   │   │   device=input_ids.device                                               │
│    920 │   │   │   │   )                                                                         │
│                                                                                                  │
│ /data/chatglm-ppo/chatglm-maths/chatglm_maths/models/modeling_chatglm.py:847 in get_masks        │
│                                                                                                  │
│    844 │   │   self.word_embeddings = new_embeddings                                             │
│    845 │                                                                                         │
│    846 │   def get_masks(self, seq, device):                                                     │
│ ❱  847 │   │   context_length = seq.index(self.config.bos_token_id)                              │
│    848 │   │   attention_mask = torch.ones((1, len(seq), len(seq)), device=device)               │
│    849 │   │   attention_mask.tril_()                                                            │
│    850 │   │   attention_mask[..., :context_length] = 1                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: 130004 is not in list

**Comment by yongzhuo** [comment]
初步看，估计是权重不一致了，最新chatglm-6b权重删除了2w图像的embedding的id。这个是最初的权重、字典

**Comment by YSLLYW** [comment]
> 初步看，估计是权重不一致了，最新chatglm-6b权重删除了2w图像的embedding的id。这个是最初的权重、字典

所以，怎么解决？

**Comment by 254288008** [comment]
> 

大佬   解决了没

**Comment by yongzhuo** [comment]
@254288008   理论上只需要把包引入改改就好。你试试呢
```
把models目录下的文件改成chatglm-6b官方最新的，可以从hunggface.co模型库下载，或者官方数据源.
configuration_chatglm.py
modeling_chatglm.py
quantization.py
tokenization_chatglm.py
```


如果要用PPO，把ppo_trainer.py也改改
```
ID_BOS = 150004
 ID_EOS = 150005
```
改成
```
 ID_BOS = 130004
 ID_EOS = 130005```

**Comment by 254288008** [comment]
> @254288008 理论上只需要把包引入改改就好。你试试呢
> 
> ```
> from chatglm_maths.models.modeling_chatglm import ChatGLMForConditionalGeneration, ChatGLMConfig
> from chatglm_maths.models.tokenization_chatglm import ChatGLMTokenizer
> ```
> 
> 改成
> 
> ```
> from transformers import ChatGLMForConditionalGeneration, ChatGLMTokenizer
> ```
> 
> 如果要用PPO，把ppo_trainer.py也改改
> 
> ```
> ID_BOS = 150004
>  ID_EOS = 150005
> ```
> 
> 改成
> 
> ```
>  ID_BOS = 130004
>  ID_EOS = 130005```
> ```


> @254288008 理论上只需要把包引入改改就好。你试试呢
> 
> ```
> from chatglm_maths.models.modeling_chatglm import ChatGLMForConditionalGeneration, ChatGLMConfig
> from chatglm_maths.models.tokenization_chatglm import ChatGLMTokenizer
> ```
> 
> 改成
> 
> ```
> from transformers import ChatGLMForConditionalGeneration, ChatGLMTokenizer
> ```
> 
> 如果要用PPO，把ppo_trainer.py也改改
> 
> ```
> ID_BOS = 150004
>  ID_EOS = 150005
> ```
> 
> 改成
> 
> ```
>  ID_BOS = 130004
>  ID_EOS = 130005```
> ```

大佬     
from chatglm_maths.models.modeling_chatglm import ChatGLMForConditionalGeneration, ChatGLMConfig
from chatglm_maths.models.tokenization_chatglm import ChatGLMTokenizer
这个是在那个文件呀    为什么没找到呢

**Comment by yongzhuo** [comment]
@254288008 
主要是把models目录下的文件改成chatglm-6b官方最新的，可以从hunggface.co模型库下载，或者官方数据源.
configuration_chatglm.py
modeling_chatglm.py
quantization.py
tokenization_chatglm.py
